- name: "Forum"
  color: "3FBE38"
  description: "Ideas related to the Forum"
- name: "Discord"
  color: "2898D8"
  description: "This idea is related to Discord"
- name: "Github"
  color: "5319E7"
  description: "This idea is related to Github (Django or related organisations)"
- name: "New Platforms"
  color: "5319E7"
  description: "A suggestion for a new platform"
- name: "Community processes"
  color: "5319E7"
- name: "DjangoProject.com"
  color: "5319E7"
- name: "Documentation"
  color: "5319E7"
# - name: "Frontend/JavaScript"
#   color: "5319E7"
# - name: "Forms"
#   color: "5319E7"
# - name: "GeoDjango"
#   color: "5319E7"
# - name: "Internationalization"
#   color: "5319E7"
# - name: "Middleware"
#   color: "5319E7"
# - name: "Migrations"
#   color: "5319E7"
# - name: "Models/ORM"
#   color: "5319E7"
# - name: "Rest APIs"
#   color: "5319E7"
# - name: "Templates"
#   color: "5319E7"
# - name: "Testing"
#   color: "5319E7"
# - name: "URLs"
#   color: "5319E7"
# - name: "Views"
#   color: "5319E7"
